# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7911351134ab6cc85456f35e61ed8e8193d763e6cb9f61c55f1349a6034dd7ae24f513b144a6366152090bb1d193da2cea173e2b11161d1f6e9dba81b6d37f41

test:
  secret_key_base: 777f8ebbeb95fd5dc03d8a87f2efeed188dfb8155e720458f25d6f1c696d4673d33b161e5cfb40b69fcc1a09415aa7abd8e3ef8024cadb41dc8f3718eb442c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
